import os
import requests


def create_pr(
    feature_name: str,
    test_cases: str,
    test_code: str,
    closure_report: str,
    branch_name: str = None,
) -> str:
    """
    Create a GitHub PR with all STLC artifacts as the PR body.
    Returns the PR URL.
    """
    token = os.environ["GITHUB_TOKEN"]
    repo = os.environ["GITHUB_REPO"]
    branch = branch_name or f"stlc/{feature_name.lower().replace(' ', '-')}"

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
    }

    body = f"""## STLC Artifacts — {feature_name}

### Test Cases
```
{test_cases[:3000]}
```

### Automation Code
```java
{test_code[:3000]}
```

### Closure Report
```
{closure_report}
```

---
Generated by STLC Orchestrator Agent
"""

    resp = requests.post(
        f"https://api.github.com/repos/{repo}/pulls",
        headers=headers,
        json={
            "title": f"[STLC] {feature_name} — Test Automation",
            "body": body,
            "head": branch,
            "base": "main",
        }
    )
    resp.raise_for_status()
    return resp.json()["html_url"]
